name: tests

on:
  push:

jobs:
  tests:

    runs-on: ubuntu-latest
    steps:
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Checkout
        uses: actions/checkout@v5
      - name: Run tests
        uses: burrunan/gradle-cache-action@v3
        with:
          arguments: test --no-daemon